[package]
name = "collab-persistence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.7"
thiserror = "1.0.30"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
lib0 = { version = "0.16.3", features = ["lib0-serde"] }
yrs = "0.16.4"
smallvec = { version="1.10", features=["write","union","const_generics","const_new"] }

[dev-dependencies]
tempfile = "3.4.0"
