[package]
name = "appflowy-collab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yrs = "0.16.4"
anyhow = "1.0.69"
thiserror = "1.0.39"
serde = {version = "1.0.157", features = ["derive"] }
lib0 = { version = "0.16.3", features = ["lib0-serde"] }
serde_json = "1.0.94"
