[workspace]
members = [
    "collab",
    "collab-derive",
    "collab-persistence",
    "collab-document",
    "collab-folder",
    "collab-database",
    "collab-sync-protocol",
    "collab-plugins",
    "collab-user",
    "collab-define"
]
