[workspace]
members = [
    "collab",
    "collab-derive",
    "collab-persistence",
    "collab-document",
    "collab-folder",
]

[patch.crates-io]
lib0 = { git = "https://github.com/toeverything/y-crdt", rev = "a3f7263" }
yrs = { git = "https://github.com/toeverything/y-crdt", rev = "a3f7263" }