[workspace]
members = [
    "collab",
    "collab-derive",
    "collab-persistence",
    "collab-database",
    "collab-plugins",
    "collab-user",
    "collab-entity",
    "collab-document",
    "collab-folder",
]

[workspace.dependencies]
collab = { workspace = true, path = "collab" }
collab-derive = { workspace = true, path = "collab-derive" }
collab-persistence = { workspace = true, path = "collab-persistence" }
collab-database = { workspace = true, path = "collab-database" }
collab-plugins = { workspace = true, path = "collab-plugins" }
collab-user = { workspace = true, path = "collab-user" }
collab-entity = { workspace = true, path = "collab-entity" }
collab-document = { workspace = true, path = "collab-document" }
collab-folder = { workspace = true, path = "collab-folder" }
yrs = "0.16.5"
anyhow = "1.0"
thiserror = "1.0.39"
serde = { version = "1.0.157", features = ["derive"] }
lib0 = { version = "0.16.3", features = ["lib0-serde"] }
serde_json = "1.0.108"
parking_lot = "0.12.1"
bytes = "1.5.0"
tracing = "0.1.22"
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
async-trait = "0.1"