[workspace]
members = [
    "collab",
    "collab-derive",
    "collab-persistence",
    "collab-document",
    "collab-folder",
    "collab-database",
    "collab-sync",
    "collab-sync-protocol",
    "collab-plugins",
    "collab-ws",
    "appflowy-integrate",
    "collab-user",
    "collab-define"
]
