[package]
name = "collab-database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { path = "../collab", features = ["rocksdb"] }
collab-derive = { path = "../collab-derive" }
collab-persistence = { path = "../collab-persistence" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.94"
thiserror = "1.0.30"
anyhow = "1.0.70"
serde_repr = "0.1"
parking_lot = "0.12.1"
tokio = { version = "1.26", features = ["rt", "sync"] }
tracing = { version = "0.1", features = ["log"] }
nanoid = "0.4.0"
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
lazy_static = "1.4.0"
lru = "0.10.0"
collab-plugins = { path = "../collab-plugins", features = ["disk_rocksdb"] }

[dev-dependencies]
tempfile = "3.4.0"
tokio = { version = "1.26", features = ["full"] }
assert-json-diff = "2.0.2"
lazy_static = "1.4.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
rand = "0.8.4"
futures = "0.3.18"
