[package]
name = "collab-database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { path = "../collab"}
collab-derive = { path = "../collab-derive"}
collab-persistence = { path = "../collab-persistence" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.30"
anyhow = "1.0.70"
serde_repr = "0.1"
parking_lot = "0.12.1"
tokio = { version = "1.26", features = ["rt", "sync"] }
tracing = { version = "0.1", features = ["log"] }
