mod child_views_test;
mod custom_section;
mod favorite_test;
mod folder_hierarchy_test;
mod load_disk;
// mod recent_views_test;
mod serde_test;
mod space_info_test;
mod trash_test;
mod util;
mod view_test;
mod workspace_test;
