[package]
name = "collab-document"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { path = "../collab" }
collab-derive = { path = "../collab-derive" }
collab-persistence = { path = "../collab-persistence" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
nanoid = "0.4.0"
thiserror = "1.0.30"
anyhow = "1.0"
parking_lot = "0.12.1"
tracing = "0.1.29"
tokio = { version = "1.26", features = ["time", "sync", "rt"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.26", features = ["full"] }
tempfile = "3.4.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
collab-plugins = { path = "../collab-plugins", features = ["rocksdb_plugin"] }