[package]
name = "collab-document"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab = { path = "../collab", features = ["rocksdb"] }
collab-derive = { path = "../collab-derive" }
collab-persistence = { path = "../collab-persistence" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
nanoid = "0.4.0"
thiserror = "1.0.30"
anyhow = "1.0.70"
parking_lot = "0.12.1"
tracing = "0.1.29"

[dev-dependencies]
tempfile = "3.4.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
