[package]
name = "collab-plugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yrs = "0.16.3"
y-sync = { version = "0.3.1" }
collab = { path = "../collab" }
collab-sync = { path = "../collab-sync", optional = true }
futures-util = { version = "0.3", features = ["sink"], optional = true }
tokio = { version = "1.26.0", features = ["net", "sync", "time"], optional = true }
tracing = { version = "0.1.37" }

[dev-dependencies]
tempfile = "3.4.0"
assert-json-diff = "2.0.2"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1.4"
dashmap = "5.4.0"
serde_json = "1.0.64"
collab-persistence = { path = "../collab-persistence" }

[features]
default = ["sync"]
sync = ["collab-sync", "futures-util", "tokio"]
