[package]
name = "collab-plugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yrs = "0.16.5"
y-sync = { version = "0.3.1" }
lib0 = { version = "0.16.3", features = ["lib0-serde"] }

#collab
collab = { path = "../collab" }
collab-define = { path = "../collab-define" }
collab-persistence = { path = "../collab-persistence", optional = true }

#sync plugin
collab-sync-protocol = { path = "../collab-sync-protocol" }

futures-util = { version = "0.3", features = ["sink"] }
tokio = { version = "1.26.0", features = ["sync"] }
tracing = { version = "0.1.37" }
parking_lot = "0.12.1"

#aws
aws-config = { version = "0.56", optional = true }
aws-sdk-dynamodb = { version = "0.29.0", optional = true }
aws-credential-types = { version = "0.56", optional = true }
rusoto_credential = { version = "0.48.0", optional = true }

anyhow = "1.0"
tokio-retry = "0.3"
async-trait = "0.1.51"
thiserror = "1.0.39"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = { version = "0.8" }
similar = { version = "2.2.1" }
tokio-stream = { version = "0.1.14", features = ["sync"] }
uuid = { version = "1.3.3", features = ["v4"] }
bytes = "1.5"

[dev-dependencies]
collab-plugins = { path = "", features = ["rocksdb_plugin", "snapshot_plugin"] }
tempfile = "3.8.0"
assert-json-diff = "2.0.2"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tokio = { version = "1.26.0", features = ["macros", "net"] }
tokio-util = { version = "0.7", features = ["codec"] }
dashmap = "5.4.0"
lib0 = { version = "0.16.3", features = ["lib0-serde"] }
nanoid = "0.4.0"
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dotenv = "0.15.0"
futures = "0.3.17"
chrono = "0.4.31"


[features]
default = ["sync_plugin"]
rocksdb_plugin = ["collab-persistence/rocksdb_persistence"]
aws_storage_plugin = ["aws-config", "aws-sdk-dynamodb", "aws-credential-types", "rusoto_credential"]
postgres_storage_plugin = ["collab-persistence/rocksdb_persistence"]
snapshot_plugin = ["collab-persistence/rocksdb_persistence"]
sync_plugin = []
snapshot = []
