[package]
name = "collab-importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collab-folder = { workspace = true }
collab-database = { workspace = true }
collab-document = { workspace = true }
collab = { workspace = true }
collab-entity = { workspace = true }
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
walkdir = "2.5.0"
uuid = "1.6.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
markdown = "1.0.0-alpha.21"
tracing.workspace = true
percent-encoding = "2.3.1"
fancy-regex = "0.13.0"
fxhash = "0.2.1"
tokio = { workspace = true, features = ["io-util", "fs"] }
rayon = "1.10.0"
sha2 = "0.10.8"
base64 = "0.22.1"
hex = "0.4.3"
zip = "2.2.0"
async-recursion = "1.1.1"
async-trait.workspace = true
<<<<<<< Updated upstream
=======
futures = "0.3.30"
async-recursion = "1.1"
>>>>>>> Stashed changes

[dev-dependencies]
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tokio = { workspace = true, features = ["full"] }
nanoid = "0.4.0"
assert-json-diff = "2.0.2"
csv = { version = "1.3.0" }
