name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: "1.65"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Install LLVM
        run: sudo apt-get install llvm

      - name: Install grcov
        run: cargo install grcov

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: Install prerequisites
        run: |
          cargo install --force cargo-make
          cargo install --force duckscript_cli
          rustup component add llvm-tools-preview

      - name: Generate code coverage report
        run: | 
          cargo make run_coverage
          

      - name: Upload code coverage report to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage.lcov
          fail_ci_if_error: true

