name: Collab-WASM

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

env:
  RUST_TOOLCHAIN: "1.75"
  CARGO_MAKE_VERSION: "0.36.6"

jobs:
  wasm_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make@${{ env.CARGO_MAKE_VERSION }}

      - name: Build
        run: cargo make wasm_build

